HEADERS_NBA_DOT_COM = {
    'Connection': 'keep-alive',
    'Cache-Control': 'max-age=0',
    'Upgrade-Insecure-Requests': '1',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36',
    'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}

PARAMETERS_PLAYER_STATS = (
    ('College', ''),
    ('Conference', ''),
    ('Country', ''),
    ('DateFrom', ''),
    ('DateTo', ''),
    ('Division', ''),
    ('DraftPick', ''),
    ('DraftYear', ''),
    ('GameScope', ''),
    ('GameSegment', ''),
    ('Height', ''),
    ('LastNGames', '0'),
    ('LeagueID', '00'),
    ('Location', ''),
    ('MeasureType', 'Base'),
    ('Month', '0'),
    ('OpponentTeamID', '0'),
    ('Outcome', ''),
    ('PORound', '0'),
    ('PaceAdjust', 'N'),
    ('PerMode', 'PerGame'),
    ('Period', '0'),
    ('PlayerExperience', ''),
    ('PlayerPosition', ''),
    ('PlusMinus', 'N'),
    ('Rank', 'N'),
    ('Season', '2018-19'),
    ('SeasonSegment', ''),
    ('SeasonType', 'Regular Season'),
    ('ShotClockRange', ''),
    ('StarterBench', ''),
    ('TeamID', '0'),
    ('TwoWay', '0'),
    ('VsConference', ''),
    ('VsDivision', ''),
    ('Weight', ''),
)

PARAMETERS_SHOT_DATA = (
    ('AheadBehind', ''),
    ('CFID', '33'),
    ('CFPARAMS', '2018-19'),
    ('ClutchTime', ''),
    ('Conference', ''),
    ('ContextFilter', ''),
    ('ContextMeasure', 'FGA'),
    ('DateFrom', ''),
    ('DateTo', ''),
    ('Division', ''),
    ('EndPeriod', '10'),
    ('EndRange', '28800'),
    ('GROUP_ID', ''),
    ('GameEventID', ''),
    ('GameID', ''),
    ('GameSegment', ''),
    ('GroupID', ''),
    ('GroupMode', ''),
    ('GroupQuantity', '5'),
    ('LastNGames', '0'),
    ('LeagueID', '00'),
    ('Location', ''),
    ('Month', '0'),
    ('OnOff', ''),
    ('OpponentTeamID', '0'),
    ('Outcome', ''),
    ('PORound', '0'),
    ('Period', '0'),
    ('PlayerID1', ''),
    ('PlayerID2', ''),
    ('PlayerID3', ''),
    ('PlayerID4', ''),
    ('PlayerID5', ''),
    ('PlayerPosition', ''),
    ('PointDiff', ''),
    ('Position', ''),
    ('RangeType', '0'),
    ('RookieYear', ''),
    ('Season', '2018-19'),
    ('SeasonSegment', ''),
    ('SeasonType', 'Regular Season'),
    ('ShotClockRange', ''),
    ('StartPeriod', '1'),
    ('StartRange', '0'),
    ('StarterBench', ''),
    ('TeamID', '0'),
    ('VsConference', ''),
    ('VsDivision', ''),
    ('VsPlayerID1', ''),
    ('VsPlayerID2', ''),
    ('VsPlayerID3', ''),
    ('VsPlayerID4', ''),
    ('VsPlayerID5', ''),
    ('VsTeamID', ''),
)



URL_PLAYER_STATS = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2018-19&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StarterBench=&TeamID=0&TwoWay=0&VsConference=&VsDivision=&Weight='

URL_PLAYER_SHOTS = 'https://stats.nba.com/stats/shotchartdetail?AheadBehind=&CFID=33&CFPARAMS=2018-19&ClutchTime=&Conference=&ContextFilter=&ContextMeasure=FGA&DateFrom=&DateTo=&Division=&EndPeriod=10&EndRange=28800&GROUP_ID=&GameEventID=&GameID=&GameSegment=&GroupID=&GroupMode=&GroupQuantity=5&LastNGames=0&LeagueID=00&Location=&Month=0&OnOff=&OpponentTeamID=0&Outcome=&PORound=0&Period=0&PlayerID={}&PlayerID1=&PlayerID2=&PlayerID3=&PlayerID4=&PlayerID5=&PlayerPosition=&PointDiff=&Position=&RangeType=0&RookieYear=&Season=2018-19&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&StartPeriod=1&StartRange=0&StarterBench=&TeamID=0&VsConference=&VsDivision=&VsPlayerID1=&VsPlayerID2=&VsPlayerID3=&VsPlayerID4=&VsPlayerID5=&VsTeamID='
